/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type WorkSample = {
  _id: string;
  _type: "workSample";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?:
    | "GRAPHIC_DESIGN"
    | "LOGOS"
    | "BRAND_IDENTITY"
    | "PACKAGING"
    | "POSTERS"
    | "SCREENPRINT"
    | "STUDIES"
    | "MOTION"
    | "TYPOGRAPHY";
  mediaType?: "image" | "video";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
  videoFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  videoUrl?: string;
  ratio?: "4/5" | "3/4" | "1/1" | "16/9" | "9/16" | "3/2";
  year?: string;
  clientOrBrand?: string;
  description?: string;
  tags?: Array<string>;
  featured?: boolean;
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type FeaturedProject = {
  _id: string;
  _type: "featuredProject";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  index?: string;
  category?: string;
  year?: string;
  role?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  tools?: Array<string>;
  summary?: string;
  intro?: string;
  context?: Array<string>;
  concept?: Array<{
    heading?: string;
    body?: string;
    _type: "conceptItem";
    _key: string;
  }>;
  pullQuote?: string;
  systemNotes?: Array<string>;
  gallery?: Array<{
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    label?: string;
    style?: "specimen" | "letter" | "grid" | "halftone" | "mesh" | "scan";
    ratio?: "3/2" | "4/5" | "16/9" | "1/1" | "3/4";
    span?: "full" | "wide" | "half" | "tall";
    _type: "galleryItem";
    _key: string;
  }>;
  video?: {
    poster?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    src?: string;
    title?: string;
  };
  featured?: boolean;
  order?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | SanityFileAssetReference
  | WorkSample
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | FeaturedProject
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../Portfolio AGY/lib/sanity/queries.ts
// Variable: FEATURED_PROJECTS_QUERY
// Query: *[_type == "featuredProject" && defined(slug.current)] | order(order asc, _createdAt desc) {    _id,    title,    "slug": slug.current,    index,    category,    year,    role,    coverImage {      asset-> {        _id,        url      },      alt,      hotspot    },    tools,    summary,    intro,    context,    concept[] {      _key,      heading,      body    },    pullQuote,    systemNotes,    gallery[] {      _key,      label,      style,      ratio,      span,      image {        asset-> {          _id,          url        },        alt,        hotspot      }    },    video {      poster {        asset-> {          _id,          url        }      },      src,      title    },    featured,    order  }
export type FEATURED_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  index: string | null;
  category: string | null;
  year: string | null;
  role: string | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  tools: Array<string> | null;
  summary: string | null;
  intro: string | null;
  context: Array<string> | null;
  concept: Array<{
    _key: string;
    heading: string | null;
    body: string | null;
  }> | null;
  pullQuote: string | null;
  systemNotes: Array<string> | null;
  gallery: Array<{
    _key: string;
    label: string | null;
    style: "grid" | "halftone" | "letter" | "mesh" | "scan" | "specimen" | null;
    ratio: "1/1" | "16/9" | "3/2" | "3/4" | "4/5" | null;
    span: "full" | "half" | "tall" | "wide" | null;
    image: {
      asset: {
        _id: string;
        url: string | null;
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
    } | null;
  }> | null;
  video: {
    poster: {
      asset: {
        _id: string;
        url: string | null;
      } | null;
    } | null;
    src: string | null;
    title: string | null;
  } | null;
  featured: boolean | null;
  order: number | null;
}>;

// Source: ../Portfolio AGY/lib/sanity/queries.ts
// Variable: FEATURED_PROJECT_BY_SLUG_QUERY
// Query: *[_type == "featuredProject" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    index,    category,    year,    role,    coverImage {      asset-> {        _id,        url      },      alt,      hotspot    },    tools,    summary,    intro,    context,    concept[] {      _key,      heading,      body    },    pullQuote,    systemNotes,    gallery[] {      _key,      label,      style,      ratio,      span,      image {        asset-> {          _id,          url        },        alt,        hotspot      }    },    video {      poster {        asset-> {          _id,          url        }      },      src,      title    },    featured  }
export type FEATURED_PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  index: string | null;
  category: string | null;
  year: string | null;
  role: string | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  tools: Array<string> | null;
  summary: string | null;
  intro: string | null;
  context: Array<string> | null;
  concept: Array<{
    _key: string;
    heading: string | null;
    body: string | null;
  }> | null;
  pullQuote: string | null;
  systemNotes: Array<string> | null;
  gallery: Array<{
    _key: string;
    label: string | null;
    style: "grid" | "halftone" | "letter" | "mesh" | "scan" | "specimen" | null;
    ratio: "1/1" | "16/9" | "3/2" | "3/4" | "4/5" | null;
    span: "full" | "half" | "tall" | "wide" | null;
    image: {
      asset: {
        _id: string;
        url: string | null;
      } | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
    } | null;
  }> | null;
  video: {
    poster: {
      asset: {
        _id: string;
        url: string | null;
      } | null;
    } | null;
    src: string | null;
    title: string | null;
  } | null;
  featured: boolean | null;
} | null;

// Source: ../Portfolio AGY/lib/sanity/queries.ts
// Variable: WORK_SAMPLES_QUERY
// Query: *[_type == "workSample" && defined(slug.current)] | order(order asc, _createdAt desc) {    _id,    title,    "slug": slug.current,    category,    mediaType,    image {      asset-> {        _id,        url,        metadata {          dimensions {            width,            height,            aspectRatio          }        }      },      alt,      hotspot    },    gallery[] {      _key,      alt,      caption,      asset-> {        _id,        url,        metadata {          dimensions {            width,            height,            aspectRatio          }        }      }    },    videoFile {      asset-> {        _id,        url      }    },    videoUrl,    ratio,    year,    clientOrBrand,    description,    tags,    featured,    order  }
export type WORK_SAMPLES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  category:
    | "BRAND_IDENTITY"
    | "GRAPHIC_DESIGN"
    | "LOGOS"
    | "MOTION"
    | "PACKAGING"
    | "POSTERS"
    | "SCREENPRINT"
    | "STUDIES"
    | "TYPOGRAPHY"
    | null;
  mediaType: "image" | "video" | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  gallery: Array<{
    _key: string;
    alt: string | null;
    caption: string | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
  }> | null;
  videoFile: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  videoUrl: string | null;
  ratio: "1/1" | "16/9" | "3/2" | "3/4" | "4/5" | "9/16" | null;
  year: string | null;
  clientOrBrand: string | null;
  description: string | null;
  tags: Array<string> | null;
  featured: boolean | null;
  order: number | null;
}>;

// Source: ../Portfolio AGY/lib/sanity/queries.ts
// Variable: WORK_SAMPLES_BY_CATEGORY_QUERY
// Query: *[_type == "workSample" && category == $category && defined(slug.current)] | order(order asc, _createdAt desc) {    _id,    title,    "slug": slug.current,    category,    mediaType,    image {      asset-> {        _id,        url,        metadata {          dimensions {            width,            height,            aspectRatio          }        }      },      alt,      hotspot    },    gallery[] {      _key,      alt,      caption,      asset-> {        _id,        url,        metadata {          dimensions {            width,            height,            aspectRatio          }        }      }    },    videoFile {      asset-> {        _id,        url      }    },    videoUrl,    ratio,    year,    clientOrBrand,    description,    tags,    featured  }
export type WORK_SAMPLES_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  category:
    | "BRAND_IDENTITY"
    | "GRAPHIC_DESIGN"
    | "LOGOS"
    | "MOTION"
    | "PACKAGING"
    | "POSTERS"
    | "SCREENPRINT"
    | "STUDIES"
    | "TYPOGRAPHY"
    | null;
  mediaType: "image" | "video" | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  gallery: Array<{
    _key: string;
    alt: string | null;
    caption: string | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
  }> | null;
  videoFile: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  videoUrl: string | null;
  ratio: "1/1" | "16/9" | "3/2" | "3/4" | "4/5" | "9/16" | null;
  year: string | null;
  clientOrBrand: string | null;
  description: string | null;
  tags: Array<string> | null;
  featured: boolean | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "featuredProject" && defined(slug.current)] | order(order asc, _createdAt desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    index,\n    category,\n    year,\n    role,\n    coverImage {\n      asset-> {\n        _id,\n        url\n      },\n      alt,\n      hotspot\n    },\n    tools,\n    summary,\n    intro,\n    context,\n    concept[] {\n      _key,\n      heading,\n      body\n    },\n    pullQuote,\n    systemNotes,\n    gallery[] {\n      _key,\n      label,\n      style,\n      ratio,\n      span,\n      image {\n        asset-> {\n          _id,\n          url\n        },\n        alt,\n        hotspot\n      }\n    },\n    video {\n      poster {\n        asset-> {\n          _id,\n          url\n        }\n      },\n      src,\n      title\n    },\n    featured,\n    order\n  }\n': FEATURED_PROJECTS_QUERY_RESULT;
    '\n  *[_type == "featuredProject" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    index,\n    category,\n    year,\n    role,\n    coverImage {\n      asset-> {\n        _id,\n        url\n      },\n      alt,\n      hotspot\n    },\n    tools,\n    summary,\n    intro,\n    context,\n    concept[] {\n      _key,\n      heading,\n      body\n    },\n    pullQuote,\n    systemNotes,\n    gallery[] {\n      _key,\n      label,\n      style,\n      ratio,\n      span,\n      image {\n        asset-> {\n          _id,\n          url\n        },\n        alt,\n        hotspot\n      }\n    },\n    video {\n      poster {\n        asset-> {\n          _id,\n          url\n        }\n      },\n      src,\n      title\n    },\n    featured\n  }\n': FEATURED_PROJECT_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "workSample" && defined(slug.current)] | order(order asc, _createdAt desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    category,\n    mediaType,\n    image {\n      asset-> {\n        _id,\n        url,\n        metadata {\n          dimensions {\n            width,\n            height,\n            aspectRatio\n          }\n        }\n      },\n      alt,\n      hotspot\n    },\n    gallery[] {\n      _key,\n      alt,\n      caption,\n      asset-> {\n        _id,\n        url,\n        metadata {\n          dimensions {\n            width,\n            height,\n            aspectRatio\n          }\n        }\n      }\n    },\n    videoFile {\n      asset-> {\n        _id,\n        url\n      }\n    },\n    videoUrl,\n    ratio,\n    year,\n    clientOrBrand,\n    description,\n    tags,\n    featured,\n    order\n  }\n': WORK_SAMPLES_QUERY_RESULT;
    '\n  *[_type == "workSample" && category == $category && defined(slug.current)] | order(order asc, _createdAt desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    category,\n    mediaType,\n    image {\n      asset-> {\n        _id,\n        url,\n        metadata {\n          dimensions {\n            width,\n            height,\n            aspectRatio\n          }\n        }\n      },\n      alt,\n      hotspot\n    },\n    gallery[] {\n      _key,\n      alt,\n      caption,\n      asset-> {\n        _id,\n        url,\n        metadata {\n          dimensions {\n            width,\n            height,\n            aspectRatio\n          }\n        }\n      }\n    },\n    videoFile {\n      asset-> {\n        _id,\n        url\n      }\n    },\n    videoUrl,\n    ratio,\n    year,\n    clientOrBrand,\n    description,\n    tags,\n    featured\n  }\n': WORK_SAMPLES_BY_CATEGORY_QUERY_RESULT;
  }
}
